/**
 * Night Sky Configuration Constants
 */

export const NightSkyConfig = {
  stars: {
    count: 200,
    minSize: 1,
    maxSize: 3,
    colors: ["#ffffff", "#f0f8ff", "#e6f3ff", "#ddeeff", "#ffff99"],
    twinkleSpeed: 0.02,
    parallaxLayers: 3,
    baseOpacityMin: 0.4,
    baseOpacityMax: 1.0,
    minTwinkleSpeed: 0.01,
    maxTwinkleSpeed: 0.05,
    twinkleChance: 0.7,
  },
  parallax: {
    far: {
      density: 0.00014,
      drift: 0.00002,
      sizeMultiplier: 1.0,
      opacityMultiplier: 0.4,
      sparkleChance: 0.0,
    },
    mid: {
      density: 0.00004,
      drift: 0.00004,
      sizeMultiplier: 2.0,
      opacityMultiplier: 0.6,
      sparkleChance: 0.05,
    },
    near: {
      density: 0.00002,
      drift: 0.00006,
      sizeMultiplier: 3.0,
      opacityMultiplier: 0.8,
      sparkleChance: 0.05,
    },
  },
  nebula: {
    count: 3,
    minRadius: 100,
    maxRadius: 200,
    controlPointCount: 8,
    embeddedStarCount: 4,
    filamentCount: 3,
    colorPalettes: [
      {
        primary: "rgba(255, 100, 180, 0.08)",
        secondary: "rgba(180, 80, 255, 0.06)",
        accent: "rgba(100, 180, 255, 0.04)",
      },
      {
        primary: "rgba(100, 150, 255, 0.08)",
        secondary: "rgba(150, 100, 255, 0.06)",
        accent: "rgba(200, 150, 255, 0.04)",
      },
      {
        primary: "rgba(255, 150, 100, 0.07)",
        secondary: "rgba(255, 100, 150, 0.05)",
        accent: "rgba(255, 200, 150, 0.03)",
      },
    ],
    glowPulseSpeed: 0.0008,
    shimmerSpeed: 0.0004,
    colorShiftSpeed: 0.0002,
    filamentWaveSpeed: 0.0006,
    baseOpacity: 0.12,
    enabledOnQuality: [] as ("high" | "medium" | "low" | "minimal")[],
    quality: {
      high: {
        filaments: true,
        embeddedStars: true,
        shimmer: true,
        colorShift: true,
      },
      medium: {
        filaments: false,
        embeddedStars: true,
        shimmer: false,
        colorShift: false,
      },
    },
  },
  constellations: {
    maxLines: 5,
    opacity: 0.3,
    twinkleSpeed: 0.003,
    enabledOnQuality: [] as ("high" | "medium" | "low" | "minimal")[],
  },
  Moon: {
    radiusPercent: 0.04,
    maxRadiusPx: 60,
    color: "#f5f5dc",
    position: {
      x: 0.8,
      y: 0.2,
    },
    driftSpeed: 0.00001,
    enabledOnQuality: ["high", "medium", "low"] as (
      | "high"
      | "medium"
      | "low"
      | "minimal"
    )[],
  },
  celestialBodies: {
    moon: {
      size: 60,
      color: "#f5f5dc",
      glowRadius: 20,
      enabled: true,
    },
    planets: {
      count: 2,
      minSize: 3,
      maxSize: 8,
      colors: ["#ff6b6b", "#4ecdc4", "#45b7d1", "#96ceb4"],
    },
  },
  shootingStars: {
    frequency: 0.001,
    minSpeed: 2,
    maxSpeed: 5,
    colors: ["#ffffff", "#ffff99", "#99ccff", "#ffcc99"],
    tailLength: 15,
  },
  ufo: {
    size: 28,
    colors: {
      hull: "#b8c4e0",
      hullDark: "#6878a0",
      dome: "rgba(200, 220, 255, 0.6)",
      domeHighlight: "rgba(255, 255, 255, 0.8)",
      shield: "rgba(100, 180, 255, 0.12)",
      beam: "#fbbf24",
      beamGlow: "rgba(251, 191, 36, 0.3)",
      lights: ["#ff6b6b", "#4ecdc4", "#ffe66d", "#95e1d3", "#a78bfa", "#f472b6"],
    },
    speed: 0.0006,
    bounceMargin: 0.1,
    turnSpeed: 0.003,
    turnVariation: 0.5,
    interval: 36000,
    enterDuration: 120,
    exitDuration: 90,
    minActiveDuration: 2400,
    maxActiveDuration: 4200,
    pauseChance: 0.004,
    pauseDuration: { min: 90, max: 180 },
    driftChance: 0.15,
    driftSpeedMultiplier: 0.4,
    scanStarChance: 0.6,
    groundScanChance: 0.25,
    justVibeChance: 0.15,
    scanDuration: { min: 90, max: 180 },
    beamChargeFrames: 25,
    shieldPulseSpeed: 0.012,
    lightChaseSpeed: 0.05,
    hoverBobSpeed: 0.015,
    hoverBobAmount: 4,
    mood: {
      excitedDecay: 360,
      startledDecay: 180,
      playfulDecay: 480,
      boredThreshold: 300,
      tirednessRate: 0.0002,
      tiredThreshold: 0.6,
      moodVisuals: {
        curious: { lightSpeed: 1.0, bobDepth: 1.0, shieldBrightness: 1.0 },
        excited: { lightSpeed: 1.8, bobDepth: 0.7, shieldBrightness: 1.4 },
        bored: { lightSpeed: 0.5, bobDepth: 1.5, shieldBrightness: 0.7 },
        startled: { lightSpeed: 2.5, bobDepth: 0.5, shieldBrightness: 1.8 },
        playful: { lightSpeed: 1.5, bobDepth: 1.2, shieldBrightness: 1.2 },
        tired: { lightSpeed: 0.3, bobDepth: 2.0, shieldBrightness: 0.5 },
      },
    },
    enabledOnQuality: ["high", "medium"] as ("high" | "medium" | "low" | "minimal")[],
  },
  comet: {
    size: 8,
    speed: 0.8,
    tailLength: 30,
    color: "#87ceeb",
    interval: 9000,
    enabledOnQuality: ["high", "medium"] as ("high" | "medium" | "low" | "minimal")[],
  },
  milkyWay: {
    bandWidthPercent: 0.15,
    pathPoints: 50,
    dustLaneCount: 4,
    starCloudCount: 6,
    baseOpacity: 0.12,
    coreOpacity: 0.2,
    edgeOpacity: 0.04,
    colors: {
      edge: "rgba(180, 200, 255, 1)",
      mid: "rgba(220, 210, 240, 1)",
      core: "rgba(255, 240, 220, 1)",
    },
    shimmerSpeed: 0.0003,
    glowPulseSpeed: 0.0008,
    dustLaneDriftSpeed: 0.0001,
    starCloudPulseSpeed: 0.002,
    enabledOnQuality: [] as ("high" | "medium" | "low" | "minimal")[],
    quality: {
      high: {
        dustLanes: true,
        starClouds: true,
        shimmer: true,
        edgeDetail: true,
      },
      medium: {
        dustLanes: false,
        starClouds: true,
        shimmer: false,
        edgeDetail: false,
      },
    },
  },
  background: {
    gradientStops: [
      { position: 0, color: "#0a0a1a" },
      { position: 0.2, color: "#0f0f24" },
      { position: 0.4, color: "#1a1a2e" },
      { position: 0.6, color: "#16213e" },
      { position: 0.8, color: "#0f3460" },
      { position: 1, color: "#0a1e3d" },
    ],
  },
  animation: {
    starDriftSpeed: 0.1,
    MoonDriftSpeed: 0.05,
    parallaxMultiplier: 0.3,
  },
} as const;

export type NightSkyConfigType = typeof NightSkyConfig;
